# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('data_execucao', models.DateField(verbose_name='data de execução')),
                ('executado', models.BooleanField()),
            ],
            options={
                'ordering': ['-data_criacao', 'executado'],
            },
        ),
    ]
