# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_execucao',
            field=models.DateField(blank=True, null=True, verbose_name='data de execução'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='executado',
            field=models.BooleanField(default=False),
        ),
    ]
