#!/usr/bin/python
import os
from minhas_tarefas import wsgi

virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/'
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    with open(virtualenv) as f:
        code = compile(f.read(), virtualenv, 'exec')
        exec(code, dict(__file__=virtualenv))
except IOError:
    pass

application = wsgi.application
